#!/bin/bash

#SBATCH --job-name=generate_tables
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=28
#SBATCH --time=01:00:00
#SBATCH --partition=teach_cpu
#SBATCH --account=coms031144
#SBATCH --output=gen_tables.out
#SBATCH --exclusive 

#lscpu

export OMP_NUM_THREADS=28

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq` 

./generate_tables
./solver
./solver
./solver
./solver


